steps:
    # build the container image
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-f', '.devops/docker/Dockerfile', '-t', 'gcr.io/wonderkind-testing/laravel-cloud-run', '.']
        # push the container image to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/wonderkind-testing/laravel-cloud-run']
        # Deploy container image to Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['beta', 'run', 'deploy', 'laravel-cloud-run', '--image', 'gcr.io/wonderkind-testing/laravel-cloud-run', '--region', 'europe-west1','--platform', 'managed', '--quiet']
images:
    - gcr.io/wonderkind-testing/laravel-cloud-run
